
version: '3.8'

services:

  backend:
    build: ./back-metro
    command: uvicorn app.main:app

  frontend:
    build: ./front-metro
    ports:
      - "3000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend

volumes:
  caddy-data:
  caddy-config: